version: "3"
services:

  hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"

    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 360000
      GRID_TIMEOUT: 360000
    networks:
      - backend-network

  chrome:
    image: selenium/node-chrome-debug
    container_name: web-automation_chrome
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 4
      NODE_MAX_INSTANCES: 4
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "9001:5900"
    links:
      - hub
    networks:
      - backend-network
networks:
  backend-network:
    external:
      name: backend